name: Generate Snake

on:
  schedule: # Execute every week
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: MihirDesh
#           svg_out_path: dist/github-contribution-grid-snake.svg
          outputs: |
            dist/github-snake.svg
            dist/github-snake-light.svg?palette=github-light

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
